import { NextRequest, NextResponse } from "next/server";

const MOCK_READINGS: Record<string, Record<string, string>> = {
  daily: {
    Aries: "The cosmos ignites your inner fire today, Aries. Mars, your ruling planet, sends bold energy your way — this is not a day to hesitate. Trust your instincts in conversations and take that first step you've been postponing.\n\nAn unexpected encounter could shift your perspective entirely. Stay open to new ideas, especially from someone younger than you. The universe rewards courage today.\n\nWatch for an opportunity around midday — it may seem small but carries great potential.\n\nLUCKY: 7|Crimson Red|11:00 AM",
    Taurus: "Venus blesses you with warmth and stability today, Taurus. Your grounded nature is your greatest asset — use it to anchor those around you who feel lost. Financial matters look favorable; a decision you've been delaying can finally be made.\n\nYour senses are heightened today — beauty, music, and good food will restore your soul. Treat yourself without guilt. The universe supports your comfort.\n\nA conversation with a close friend holds wisdom you've been searching for.\n\nLUCKY: 14|Emerald Green|3:00 PM",
    Gemini: "Mercury sharpens your mind to a fine edge today, Gemini. Words flow effortlessly — use this gift wisely in negotiations or creative writing. Your curiosity leads you to a discovery that excites your intellect deeply.\n\nDuality is your strength today. Balance your social energy with quiet reflection. Both halves of your nature need expression to feel whole and at peace.\n\nA message you receive this evening carries important news worth acting upon.\n\nLUCKY: 21|Golden Yellow|7:00 PM",
    Cancer: "The Moon, your cosmic mother, wraps you in intuitive clarity today, Cancer. Your empathy is a superpower — use it to heal a relationship that needs tender attention. Home and family matters find resolution under this gentle lunar energy.\n\nTrust the feelings that surface without overthinking them. Your subconscious knows what your mind has not yet accepted. Breathe and listen within.\n\nAn old memory surfaces that brings unexpected joy and direction.\n\nLUCKY: 3|Silver White|9:00 AM",
    Leo: "The Sun, your radiant ruler, amplifies your natural magnetism today, Leo. You walk into any room and light it up — own this energy with grace and humility. Creative projects receive cosmic blessing; begin something bold and expressive.\n\nLeadership is called upon today. Someone looks to you for guidance — rise to this moment with both strength and compassion. Your generosity inspires loyalty.\n\nA long-awaited recognition or compliment arrives at the perfect moment.\n\nLUCKY: 19|Royal Gold|12:00 PM",
    Virgo: "Mercury gifts you extraordinary analytical clarity today, Virgo. Details that others miss become crystal clear to your discerning eye. Use this precision to solve a problem that has lingered for weeks without resolution.\n\nService to others brings deep satisfaction today. A small act of kindness creates ripples far beyond what you can see. Your practical wisdom is a gift to the world.\n\nOrganizing your space or thoughts creates space for a breakthrough idea.\n\nLUCKY: 6|Forest Green|8:00 AM",
    Libra: "Venus graces your day with harmony and aesthetic beauty, Libra. Balance is your birthright — restore it in a relationship that has felt slightly off. Diplomacy comes naturally; use it to bridge a gap between opposing forces today.\n\nArt, music, or beauty in any form deeply nourishes your soul right now. Schedule time for something purely pleasurable. You deserve beauty without reason.\n\nA fair decision you make today creates lasting peace in your environment.\n\nLUCKY: 11|Rose Pink|2:00 PM",
    Scorpio: "Pluto stirs the depths of your perception today, Scorpio. You see beneath surfaces and through illusions with penetrating clarity. A truth that has been hidden is finally revealed — you were right to trust your instincts all along.\n\nTransformation is available to you today. Release what no longer serves your evolution with courage and finality. Every ending you embrace becomes a powerful new beginning.\n\nA deep conversation tonight reveals a soul connection of rare significance.\n\nLUCKY: 8|Midnight Black|10:00 PM",
    Sagittarius: "Jupiter expands your horizon with boundless optimism today, Sagittarius. Adventure calls — even a small deviation from routine opens surprising doors. Your philosophical mind finds answers to questions that have long occupied your spirit.\n\nTeaching or sharing your wisdom brings unexpected joy today. Your enthusiasm is contagious and inspires those around you to dream bigger. Spread that fire freely.\n\nAn opportunity connected to travel or higher learning deserves serious attention.\n\nLUCKY: 33|Purple Violet|4:00 PM",
    Capricorn: "Saturn rewards your discipline with tangible progress today, Capricorn. The hard work you have quietly invested begins to show visible results. Authority figures notice your competence — stay visible and speak your vision clearly.\n\nPatience is your sacred practice today. What feels slow is actually building on solid rock. Trust the timeline the universe has set for your greatest ambitions.\n\nA practical decision made today saves significant time and energy next month.\n\nLUCKY: 4|Charcoal Grey|6:00 AM",
    Aquarius: "Uranus sparks your innovative genius with electric inspiration today, Aquarius. A revolutionary idea arrives fully formed — write it down immediately before it fades. Your vision for a better future is not just a dream but a genuine possibility.\n\nCommunity and connection feed your humanitarian spirit. Reach out to your network today — collaboration unlocks what solitude cannot. Together you achieve the extraordinary.\n\nAn unconventional approach to an old problem yields a surprisingly elegant solution.\n\nLUCKY: 17|Electric Blue|5:00 PM",
    Pisces: "Neptune dissolves all boundaries between you and the divine today, Pisces. Your artistic and intuitive gifts are heightened to extraordinary levels. Creative expression becomes a portal to healing — let it flow without judgment or restraint.\n\nCompassion without losing yourself is today's spiritual lesson. You can hold space for others while honoring your own sacred energy. Both matter equally and fully.\n\nA dream or quiet moment of stillness carries a message meant only for you.\n\nLUCKY: 12|Ocean Blue|8:00 PM",
  },
  love: {
    Aries: "Venus ignites passionate sparks in your love life today, Aries. If single, a bold introduction could lead somewhere meaningful — take the initiative you've been hesitating on. If partnered, surprise your person with spontaneous affection and watch the magic unfold.\n\nFor singles, Sagittarius or Leo energy surrounds your romantic destiny right now. For couples, reignite the adventurous spirit you shared at the beginning of your journey together.\n\nGemini is your most compatible sign this week for deep meaningful connection.\n\nLUCKY: Sagittarius|Passion|Friday",
    Taurus: "Venus, your ruling planet, creates a deeply sensual romantic atmosphere today. Love expressed through touch, shared meals, or simple presence carries extraordinary power right now. Don't underestimate the magic of ordinary moments spent together with care.\n\nFor singles, someone stable and trustworthy is entering your sphere — look for them in familiar places you already love. For couples, a heartfelt conversation deepens your bond beautifully.\n\nCancer is your most compatible sign this week for emotional depth.\n\nLUCKY: Cancer|Trust|Wednesday",
    Gemini: "Mercury makes you irresistibly charming and witty in love today, Gemini. Your words carry romantic power — use them to express what your heart has been holding back. A meaningful conversation transforms a good connection into something truly extraordinary.\n\nFor singles, someone intellectually stimulating is nearby — connect through ideas and laughter first. For couples, try something completely new together to reignite shared excitement.\n\nLibra is your most compatible sign this week for intellectual romance.\n\nLUCKY: Libra|Communicate|Thursday",
    Cancer: "The Moon heightens your emotional intuition in matters of love today. Your nurturing nature draws people to you like a warm light in the darkness. Allow yourself to be vulnerable — your openness creates the deep connection you truly crave.\n\nFor singles, someone who needs your gentle strength is close by — let them see your warmth. For couples, creating a cozy sanctuary together strengthens your bond immeasurably.\n\nScorpio is your most compatible sign this week for soul-level connection.\n\nLUCKY: Scorpio|Nurture|Monday",
    Leo: "The Sun radiates through your love life with golden warmth today, Leo. Your generous heart and magnetic presence make you utterly irresistible to others. Express your feelings with the dramatic flair that is authentically and beautifully yours.\n\nFor singles, someone who truly appreciates your light is ready to adore you — let them. For couples, grand romantic gestures land perfectly right now. Go all in with love.\n\nAries is your most compatible sign this week for passionate connection.\n\nLUCKY: Aries|Adore|Saturday",
    Virgo: "Mercury refines your discernment in love matters with beautiful clarity today. You see potential partners clearly — both their gifts and their growth edges. This clarity is a blessing, not a barrier, on your path to lasting authentic love.\n\nFor singles, quality matters far more than quantity — trust your refined taste completely. For couples, showing care through thoughtful practical acts speaks volumes of deep devotion.\n\nCapricorn is your most compatible sign this week for grounded love.\n\nLUCKY: Capricorn|Devotion|Tuesday",
    Libra: "Venus fills your love life with beauty, balance, and romantic possibility today. You naturally create harmony in relationships — this gift is magnetic and rare. Let your authentic charm shine without dimming yourself to accommodate others.\n\nFor singles, someone aesthetically and intellectually aligned with you is near — notice them. For couples, creating beauty together — cooking, decorating, art — deepens your bond.\n\nGemini is your most compatible sign this week for balanced romance.\n\nLUCKY: Gemini|Harmony|Friday",
    Scorpio: "Pluto intensifies every romantic connection with transformative depth today. You desire a love that goes soul-deep — nothing superficial satisfies your hungry heart. Trust the magnetic pull you feel; it rarely leads you astray in matters of the heart.\n\nFor singles, an intense meaningful encounter is approaching — stay emotionally open and unguarded. For couples, deep vulnerability shared tonight creates an unbreakable bond of trust.\n\nPisces is your most compatible sign this week for soulmate energy.\n\nLUCKY: Pisces|Surrender|Tuesday",
    Sagittarius: "Jupiter expands your romantic horizons with exciting new possibilities today. Love feels like an adventure — embrace the journey without needing to know the destination. Your optimism and freedom-loving spirit attract someone who matches your magnificent energy.\n\nFor singles, someone from a different background or culture brings exciting new perspective. For couples, planning a future adventure together reignites the spark beautifully.\n\nAquarius is your most compatible sign this week for adventurous love.\n\nLUCKY: Aquarius|Adventure|Sunday",
    Capricorn: "Saturn brings a serious and deeply meaningful romantic energy today, Capricorn. You value commitment and substance in love — these qualities now attract exactly the right person. Patience in matters of the heart is your greatest romantic virtue and strength.\n\nFor singles, someone ambitious and reliable is entering your orbit — look closely. For couples, discussing long-term plans and shared dreams strengthens your foundation beautifully.\n\nTaurus is your most compatible sign this week for lasting love.\n\nLUCKY: Taurus|Commitment|Wednesday",
    Aquarius: "Uranus brings unexpected romantic electricity into your day today, Aquarius. Love surprises you in the most unconventional and delightful way — embrace it fully. Your authentic quirky self is your greatest romantic asset; never hide it for anyone.\n\nFor singles, someone uniquely different from your usual type awakens something new. For couples, breaking routine together creates fresh excitement and renewed appreciation.\n\nGemini is your most compatible sign this week for intellectual love.\n\nLUCKY: Gemini|Authenticity|Thursday",
    Pisces: "Neptune dissolves all walls around your heart with gentle loving energy today. Your romantic sensitivity is a rare and precious gift in this world — honor it. A soul-deep connection is available to you now if you open yourself fully to receiving.\n\nFor singles, someone artistic or spiritually inclined resonates with your deepest self. For couples, sharing your dreams and innermost feelings creates sacred intimacy between you.\n\nScorpio is your most compatible sign this week for mystical deep love.\n\nLUCKY: Scorpio|Surrender|Monday",
  },
  career: {
    Aries: "Mars fuels your professional ambitions with unstoppable fire this week, Aries. Take bold decisive action on a project you've been cautiously circling — the time for hesitation has definitively passed. Your leadership presence commands respect and opens important doors.\n\nFinancially, an investment opportunity deserves careful but swift evaluation. Your instincts about money are sharp right now — trust them while doing your due diligence. A calculated risk pays off handsomely.\n\nSpeak up in meetings — your ideas deserve to be heard loudly and clearly.\n\nLUCKY: 9|Tuesday|Rise Boldly",
    Taurus: "Venus and Jupiter align to bring financial abundance into your professional sphere today. A slow-building opportunity finally reaches its harvest moment — be ready to receive it graciously. Your reliability and persistence are being noticed and valued at the highest levels.\n\nA practical financial decision made this week creates long-term security and peace. Avoid impulsive spending and focus instead on building your foundation brick by careful brick.\n\nA collaboration offer arrives that aligns perfectly with your long-term goals.\n\nLUCKY: 6|Friday|Build Steady",
    Gemini: "Mercury supercharges your professional communication skills to brilliant effect today. A presentation, pitch, or important negotiation goes exceptionally well — your words land with precision and impact. Multiple income streams deserve your inventive and agile attention right now.\n\nYour networking ability is your greatest financial asset this week — use it actively. Reach out to connections you've been meaning to contact; one holds the key to a breakthrough.\n\nA side project you've been developing quietly is ready to be shared with the world.\n\nLUCKY: 5|Wednesday|Connect Widely",
    Cancer: "The Moon illuminates your professional intuition with extraordinary clarity today. Trust your gut feelings about a business decision even when logic seems to point elsewhere. Your emotional intelligence in the workplace is a rare leadership gift others deeply value.\n\nHome-based income or a business connected to nurturing others shows great promise. Financial security through helping people aligns perfectly with your deepest purpose and values.\n\nA mentor figure offers guidance that redirects your career in a powerful positive way.\n\nLUCKY: 2|Monday|Trust Instincts",
    Leo: "The Sun spotlights your professional talents for all the right people to see today. This is your moment to shine publicly — don't hold back from visibility or recognition. A creative project or performance-based role brings both fulfillment and financial reward.\n\nYour personal brand is your greatest financial asset — invest in how you present yourself. Leadership opportunities that arise this week are meant for you; accept them with confident grace.\n\nA bold creative decision made today leads to unexpected financial opportunity next month.\n\nLUCKY: 1|Sunday|Shine Bright",
    Virgo: "Mercury perfects your professional analysis and problem-solving capabilities today. A complex work challenge yields to your methodical and thorough approach with elegant ease. Your attention to detail saves a project from a costly mistake others completely missed.\n\nFinancially, careful budgeting and organization create surprising abundance and security. Review your expenses and find where small savings compound into meaningful financial freedom.\n\nA technical skill you've been developing quietly becomes extremely valuable very soon.\n\nLUCKY: 4|Thursday|Refine Craft",
    Libra: "Venus brings diplomatic harmony to your professional relationships today, Libra. A workplace conflict finds elegant resolution through your natural mediating abilities. Partnerships and collaborations are especially favored — seek them out actively and deliberately.\n\nBalance between earning and spending requires your conscious attention this week. A financial partnership or joint venture deserves serious and optimistic consideration right now.\n\nA creative collaboration opportunity arrives that combines your talents with perfect complement.\n\nLUCKY: 7|Friday|Partner Wisely",
    Scorpio: "Pluto gives you penetrating insight into workplace power dynamics today, Scorpio. You see clearly what others cannot — use this knowledge with strategic wisdom and integrity. A research project or investigative work reveals something of significant professional and financial value.\n\nTransformative financial decisions are available to you now — trust your deep instincts completely. An investment in your own growth and education yields the highest possible return.\n\nA hidden opportunity in your current role is waiting to be claimed by you alone.\n\nLUCKY: 8|Tuesday|Dig Deeper",
    Sagittarius: "Jupiter expands your professional opportunities to exciting new horizons today. A chance to teach, travel, or work internationally aligns with your expansive professional vision. Your optimism and broad worldview make you invaluable in any collaborative team environment.\n\nFinancial growth comes through expanding your knowledge and skill base boldly. Invest in learning something new — the return on this investment exceeds all expectations significantly.\n\nA long-distance connection or foreign client brings unexpected but welcome financial opportunity.\n\nLUCKY: 3|Thursday|Expand Horizons",
    Capricorn: "Saturn rewards your long-term professional strategy with concrete tangible results today. The steady disciplined work you've been doing quietly is noticed and appreciated by those above. Authority, responsibility, and the recognition you've earned are all within your grasp now.\n\nFinancial planning for the future is especially powerful and effective right now. Review your long-term strategy and make the adjustments that compound your wealth over decades.\n\nA promotion or professional advancement you've been working toward is closer than you think.\n\nLUCKY: 10|Saturday|Stay Course",
    Aquarius: "Uranus sparks revolutionary professional ideas that could reshape your entire career today. An unconventional approach to a persistent problem creates breakthrough results nobody expected. Technology, innovation, and forward-thinking position you ahead of every curve in your industry.\n\nMultiple income streams through technology or community building show exceptional promise now. Your unique perspective on the future has real and immediate financial value — monetize it.\n\nA sudden unexpected career opportunity arrives that perfectly aligns with your true vision.\n\nLUCKY: 11|Wednesday|Innovate Now",
    Pisces: "Neptune inspires your professional creativity to extraordinary and transcendent heights today. Artistic, healing, or spiritual work carries exceptional financial potential right now — pursue it. Your compassionate approach to business creates deep loyal relationships that generate lasting income.\n\nTrust the creative vision that keeps returning to your mind — it has genuine market value. Financial flow comes when you align your work completely with your highest spiritual purpose.\n\nA creative project you've been dreaming about is ready to become your greatest professional achievement.\n\nLUCKY: 7|Monday|Flow Freely",
  },
  spiritual: {
    Aries: "Mars ignites a powerful spiritual awakening within you today, Aries. Your warrior spirit is being called to fight not outward battles but the inner ones that truly matter. The courage you display in the world must now be turned inward with fierce and loving honesty.\n\nMeditate on where you are holding back your authentic self from full expression. The fire within you is sacred — tend it with both discipline and wild freedom. Your soul craves action aligned with deepest purpose.\n\nA moment of fierce stillness today reveals your truest and most powerful self.\n\nLUCKY: Red Jasper|Courage|Root Chakra",
    Taurus: "Venus grounds your spiritual practice in the sacred beauty of the physical world today. Your body is your temple — treat it with the reverence it deserves through nourishment and rest. Nature holds profound healing medicine for your soul right now; seek it out deliberately.\n\nSlowing down is your spiritual practice today. In stillness, the divine speaks in whispers only a patient heart can hear clearly. Release the need to produce and simply allow yourself to be.\n\nA walk in nature or quiet time with earth beneath your feet restores everything.\n\nLUCKY: Rose Quartz|Peace|Heart Chakra",
    Gemini: "Mercury connects your mind to higher spiritual frequencies of truth today, Gemini. The books, conversations, and ideas you encounter carry divine messages specifically meant for you. Your intellect is a spiritual instrument — let it seek wisdom rather than mere information.\n\nJournaling or automatic writing opens a direct channel to your higher self today. The words that flow without thinking hold the truths your conscious mind has been avoiding.\n\nA conversation or text today carries a spiritual message disguised as ordinary exchange.\n\nLUCKY: Clear Quartz|Clarity|Throat Chakra",
    Cancer: "The Moon draws you deep into the sacred waters of your inner world today, Cancer. Your emotions are not obstacles to spirituality — they are the very path itself for you. Feel everything fully and allow each feeling to be a doorway to divine understanding.\n\nAncestral healing is available to you in this sacred moment. Honor those who came before you through ceremony, memory, or simple gratitude for the gifts they carried.\n\nA dream or strong intuition tonight carries a message from beyond the ordinary.\n\nLUCKY: Moonstone|Receive|Sacral Chakra",
    Leo: "The Sun illuminates your divine purpose with radiant unmistakable clarity today, Leo. Your soul came here to shine — not for ego but as genuine service to a world that needs your light. Spiritual pride dissolves when you realize your gifts belong to something greater.\n\nCreative expression is your prayer and your meditation today. When you create from your deepest authentic self, you touch the divine and allow others to feel it too.\n\nA moment of pure creative joy today reconnects you to your sacred original purpose.\n\nLUCKY: Sunstone|Radiate|Solar Plexus Chakra",
    Virgo: "Mercury refines your spiritual discernment to extraordinary precision today, Virgo. Your gift for seeing what needs healing in yourself and others is a sacred calling and responsibility. Service as a spiritual practice transforms mundane tasks into acts of profound devotion.\n\nPurifying your environment — physical, mental, and emotional — creates sacred space for the divine. Let go of what clutters your inner temple with the same care you give your outer space.\n\nA healing practice you adopt today becomes a cornerstone of your spiritual journey.\n\nLUCKY: Amazonite|Purify|Crown Chakra",
    Libra: "Venus harmonizes your spiritual life with beauty, balance, and divine grace today, Libra. Your soul seeks the sacred in symmetry and in the relationships that mirror your highest self. Every meaningful connection you have is a spiritual teacher offering precise lessons.\n\nBalance between spiritual seeking and worldly engagement is your practice today. You need not choose between heaven and earth — your path is to beautifully embody both.\n\nA moment of profound beauty today — in art, nature, or human connection — opens your heart completely.\n\nLUCKY: Lapis Lazuli|Balance|Heart Chakra",
    Scorpio: "Pluto invites you into the deepest and most transformative spiritual waters today, Scorpio. Death and rebirth are your sacred spiritual cycle — surrender to what is dying within you. On the other side of this letting go lives a version of yourself that is completely free.\n\nShadow work is your most powerful spiritual practice right now. Face what hides in the darkness of your psyche with compassionate curiosity rather than shame or fear.\n\nA profound spiritual truth reveals itself in the very thing you've been most afraid to examine.\n\nLUCKY: Obsidian|Transform|Third Eye Chakra",
    Sagittarius: "Jupiter expands your spiritual vision to encompass the entire magnificent cosmos today. Your soul is a seeker — honor this sacred calling by following the questions that most ignite you. Philosophy, sacred texts, and cross-cultural wisdom all hold keys meant for your specific journey.\n\nA pilgrimage — physical or metaphorical — calls to your adventurous spiritual heart today. The path itself is the teacher; the destination is merely the beginning of the next sacred journey.\n\nA teacher, book, or encounter today expands your spiritual understanding beyond all previous limits.\n\nLUCKY: Amethyst|Seek|Crown Chakra",
    Capricorn: "Saturn brings ancient spiritual discipline and sacred structure to your practice today. Your soul thrives with consistent spiritual routine — meditation, prayer, and contemplation done daily. The mountain you climb spiritually is built one faithful step at a time without exception.\n\nYour relationship with time is a spiritual lesson right now. Every moment is both perfectly timed and an opportunity to align more fully with divine purpose and presence.\n\nA long-term spiritual commitment made today creates profound transformation over the coming years.\n\nLUCKY: Black Tourmaline|Discipline|Root Chakra",
    Aquarius: "Uranus awakens your spiritual genius with sudden electric divine inspiration today. You receive cosmic downloads that feel ahead of their time because they genuinely are — trust them. Your spiritual path is beautifully unconventional and that is precisely its sacred power.\n\nCollective consciousness and universal love are your spiritual home today. Meditation on humanity's interconnection and your role within it opens profound channels of guidance.\n\nA sudden spiritual insight today completely revolutionizes how you understand your life's purpose.\n\nLUCKY: Labradorite|Awaken|Third Eye Chakra",
    Pisces: "Neptune dissolves all illusions of separation between you and the divine today, Pisces. You are closer to source energy than almost any other sign — honor this sacred gift with gratitude. Your dreams, visions, and intuitions are direct messages from the universe meant for you.\n\nMeditation, art, music, and time near water all deepen your spiritual connection profoundly today. Allow yourself to float in the cosmic ocean of consciousness without needing to control the current.\n\nA mystical experience today confirms that you are exactly where your soul needs to be.\n\nLUCKY: Aquamarine|Surrender|Crown Chakra",
  },
};

export async function POST(req: NextRequest) {
  try {
    const { signName, readingType } = await req.json();

    const readings = MOCK_READINGS[readingType];
    const text = readings?.[signName] ?? readings?.["Aries"] ?? "";

    // Simulate a small delay for realism
    await new Promise(resolve => setTimeout(resolve, 600));

    return NextResponse.json({ text });
  } catch (error) {
    console.error("Error:", error);
    return NextResponse.json({ error: "Something went wrong" }, { status: 500 });
  }
}